### ISSUE TITLE
Allow to specify weighting

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/graphhopper-navigation#30]
Maybe we could include the weighting in the profile, so that we can pass for example `car_shortest`.

**Comment by easbar** [comment]
Not sure if I understand what you mean, but the current idea (for GH core) is that all 'profiles' (vehicle/weighting) combinations are configured on the server and each of these profiles/configurations will have a unique name. Passing this name using the new  `profile` url-parameter will then select this profile/vehicle/weighting. The vehicle/weighting parameters will be deprecated, but there will be a compatibility layer that can be used to translate them into a corresponding profile name. Note that the profile parameter has not been implemented yet...

Also see this issue: https://github.com/graphhopper/graphhopper/issues/1859

**Comment by boldtrn** [comment]
Ah I see, thanks for the pointer @easbar, this could indeed solve this issue already.

The underlying issue here is that the Android SDK has no option to select a weighting, so I thought about how this could be solved in this case with passing something like `profile_weighting`, which indeed sounds similar to the linked issue. So I guess this will be auto-solved, once 1859 will be completed, maybe it's not worth to put more effort into this issue then and we should close it?

**Comment by boldtrn** [comment]
Ok, now that we do have profiles in the core, how should we proceed here?

Currently, it is possible to simply pass vehicles and we will always pick the fastest weighting.

So I think a good first step could be to check if the passed String equals a profile, if yes, we set this as the profile.

If not, we could fall back to our current approach to only resolve the vehicle and assume a fastest weighting.

**Comment by boldtrn** [comment]
Related to: https://github.com/graphhopper/graphhopper-navigation/commit/f1b9108e330fd211ed0e796801232f628e97c2e5

**Comment by easbar** [comment]
Can we make certain assumptions about the profile names here? For example as long as the car/fastest profile is named `car` (which is the case on graphhopper.com), all we need to do is translate `mapboxProfile=driving` into `profile=car`. It looks like we are making such assumptions anyway, because in case, e.g. the `bike` vehicle was missing we would not be able to support mapbox `cycling`. To me the cleanest approach seems to enforce the required profiles in `NavigateResource` (it does not work unless there is a car,foot and bike profile so if one of the is missing throw an error) and then either hard-code the mapping `cycling->bike` etc. or maybe even make this configurable (so we can specify something like `cycling->my_fancy_bike,driving->my_shiny_car` etc.)

**Comment by easbar** [comment]
Or maybe I did not understand what this issue was about initially. The navigation SDK is supposed to implement the Mapbox SDK API, but this does not seem to have a `weighting` parameter?

**Comment by boldtrn** [comment]
> Can we make certain assumptions about the existing profiles (and their names) here?

I would actually like to avoid that, if possible. That is currently, a downside of the profile approach IMHO. Profile names can be any string and might change at any time. So if we rely for example on a profile named `car_fastest` and we change this to `car` we will get unexpected exceptions.

In my opinion it would be great if the ProfileResolver could provide a profile like:

`ProfileResolver.getProfile(String vehicle, [String weighting], [turn cost, ...])`

In my opinion, the ProfileResolver is too strongly coupled with the RouteResource right now.

> The navigation SDK is supposed to implement the Mapbox SDK API, but this does not seem to have a weighting parameter?

The way I understand the navigation endpoint is to provide a way to make GraphHopper compatible with the navigation SDK. One of the great things about the GraphHopper API is that it provides a lot of different vehicles like trucks, scooters, different bicycles, etc.

The GraphHopper API has that flexibility to choose the weigthing and vehicle. So I think we should provide that feature. With the profile approach in GraphHopper it seems to me that we have a nice way of doing that.

**Comment by easbar** [comment]
> I would actually like to avoid that, if possible. 

But we already do this :) I mean gh-navigation supports mapbox's `cycling`,`driving`, etc. no? So there has to be a car,bike,foot flag encoder. If the underlying GraphHopper instance was configured another way it would not work. By enforcing I just mean checking that this assumption we are making implicitly is actually checked. For profiles its the same thing just that instead of these flag encoders we now need the according profiles. Regarding the names I agree it seems a bit fragile to simply assume that the car profile is named `car`, that is why I suggested to make the mapping between mapbox profiles and GH profile names configurable. I do not see how this a downside of the profile approach its basically the same as before: Previously we were configuring vehicles (flag encoders) and now we are configuring profiles (and (still) flag encoders :)).

> In my opinion it would be great if the ProfileResolver could provide a profile like:
> ProfileResolver.getProfile(String vehicle, [String weighting], [turn cost, ...])
> In my opinion, the ProfileResolver is too strongly coupled with the RouteResource right now.

Why do we need a ProfileResolver for GH-navigation in the first place? The only purpose of this class is translating legacy requests to profile names. But for `/navigate` there never were any legacy requests (like the ones for /route)? You could only specify the mapbox profile (`cycling` etc.), but not `vehicle`, `weighting`, `turn_costs` etc., right? To me it seems like we need *another* profile resolver here, which is doing something far simpler: It just takes the mapbox profile and maps it to a GH profile. If we want to make this mapping configurable we could inject the thing that does this into NavigateResource for example?

> The GraphHopper API has that flexibility to choose the weigthing and vehicle. So I think we should provide that feature. With the profile approach in GraphHopper it seems to me that we have a nice way of doing that.

Maybe this is the problem. GraphHopper API let you choose the weighting and vehicle independently from each other and with the profiles we are moving away from this. It is still supported but with the new approach you would rather setup the possible vehicle/weighting pairs upfront, give each of them a name and then use this name to choose one of them for your request. With the profiles approach you would probably add some more options for the mapbox profile parameter (and map them to some more GH profiles), like `short_distance_driving` would be mapped to a profile looking like that:

```yaml
profiles:
   - name: does_not_really_matter_in_case_we_make_the_mapping_configurable
     vehicle: car
     weighting: shortest
```

**Comment by karussell** [comment]
Sorry, the confusion probably comes from my recent change where I introduced the resolver temporarily to make it working (really fast) ;)

Will remove the (legacy!) resolver now and map to a fixed profile "car" etc.

The suggestion to make the mapping of mapbox stuff to ours configurable is a good one and we should approach this in a separate issue I think. The only reason I did not do this earlier was a production test for RouteResourceTest that requires non-standard profile name "car_fastest". But for the public API as well as normal local setup we can for now assume the static profile names (which can be configurable later)

**Comment by karussell** [comment]
Ok, made the mapping configurable. In total this is now even less code :)

https://github.com/graphhopper/graphhopper-navigation/commit/aeaaaf0a26db08c0fc736ca06a395defe75dacf0

**Comment by boldtrn** [comment]
> I mean gh-navigation supports mapbox's cycling,driving, etc. no? So there has to be a car,bike,foot flag encoder. If the underlying GraphHopper instance was configured another way it would not work.

Yes, but this relies on the encoder name, which is relatively static. You would need to change this in the code. Profile names can be changed in the config and it seems to me that I can change them to more or less any value without breaking GraphHopper, it's just the name I use when requesting a route for the profile. It shouldn't be hardcoded IMHO.

If the names have meanings, we shouldn't make them configurable that easily IMHO (but that might be a discussion we should be doing in the forum :)?).

My expectation would be if I don't import for example the bike profile but request it, then I get a profile not configured exception, which would be correct.

> But for /navigate there never were any legacy requests (like the ones for /route)? You could only specify the mapbox profile (cycling etc.), but not vehicle, weighting, turn_costs etc., right?

You could specify any vehicle. Weighting, turncost etc. was not available.

> Ok, made the mapping configurable. In total this is now even less code :)

Awesome, thanks for the fast fix this looks really clean :). The way I see it is that this fixes this issue, right, so we can close here?

**Comment by karussell** [comment]
> Awesome, thanks for the fast fix this looks really clean :). The way I see it is that this fixes this issue, right, so we can close here?

Ok :)
